Rails:
  Enable: true
AllCops:
  TargetRubyVersion: 2.4.2
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - !ruby/regexp /old_and_unused.rb$/
    - 'spec/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'Capfile'
    - 'lib/capistrano/tasks/unicorn.rake'
    - 'lib/tasks/**/*.rake'
    - 'node_modules/**/*'

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

Style/AsciiComments:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Style/NumericPredicate:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20
